package rc.unesp.br.lcp.beans;
// Generated 27/07/2015 23:54:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contabancaria generated by hbm2java
 */
public class Contabancaria  implements java.io.Serializable {
  
     public static final String ID_CONTA = "idContaBancaria";
     public static final String ID_BANCO = "idBanco";
  

     private Integer idContaBancaria;
     private Banco banco;
     private String agencia;
     private String conta;
     private String idBanco;
     private Set usuarios = new HashSet(0);

    public Contabancaria() {
    }

	
    public Contabancaria(Banco banco) {
        this.banco = banco;
    }
    public Contabancaria(Banco banco, Integer idContaBancaria, String agencia, String conta, String idBanco, Set usuarios) {
       this.banco = banco;
       this.idContaBancaria = idContaBancaria;
       this.agencia = agencia;
       this.conta = conta;
       this.idBanco = idBanco;
       this.usuarios = usuarios;
    }
   
    public Integer getIdContaBancaria() {
        return this.idContaBancaria;
    }
    
    public void setIdContaBancaria(Integer idContaBancaria) {
        this.idContaBancaria = idContaBancaria;
    }
    public Banco getBanco() {
        return this.banco;
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }
    public String getConta() {
        return this.conta;
    }
    
    public void setConta(String conta) {
        this.conta = conta;
    }
    public String getIdBanco() {
        return this.idBanco;
    }
    
    public void setIdBanco(String idBanco) {
        this.idBanco = idBanco;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


