package rc.unesp.br.lcp.beans;
// Generated 27/07/2015 23:54:14 by Hibernate Tools 4.3.1

/**
 * Contabancaria generated by hbm2java
 */
public class ContaBancaria  implements java.io.Serializable {
  
     public static final String ID_CONTA = "idContaBancaria";  

     private Integer idContaBancaria;
     private Banco banco;
     private String agencia;
     private String conta;

    public ContaBancaria() {
    }

	
    public ContaBancaria(Banco banco) {
        this.banco = banco;
    }
    public ContaBancaria(Integer idContaBancaria, Banco banco, String agencia, String conta) {
       this.banco = banco;
       this.idContaBancaria = idContaBancaria;
       this.agencia = agencia;
       this.conta = conta;
    }
   
    public Integer getIdContaBancaria() {
        return this.idContaBancaria;
    }
    
    public void setIdContaBancaria(Integer idContaBancaria) {
        this.idContaBancaria = idContaBancaria;
    }
    public Banco getBanco() {
        return this.banco;
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }
    public String getConta() {
        return this.conta;
    }
    
    public void setConta(String conta) {
        this.conta = conta;
    }
}


