package rc.unesp.br.lcp.beans;
// Generated 27/07/2015 23:54:14 by Hibernate Tools 4.3.1

/**
 * Despesa generated by hbm2java
 */
public class Despesa implements java.io.Serializable {

    public static final String ID_DESPESA = "idDespesa";
    public static final String DESCRICAO = "descricao";
    public static final String PRECO = "preco";
    public static final String ID_USUARIO = "usuario";

    private Integer idDespesa;
    private Usuario usuarioByIdUsuario;
    private String descricao;
    private Double preco;

    public Despesa() {
    }

    public Despesa(Integer idDespesa, Usuario usuarioByIdUsuario, String descricao, Double preco) {
        this.idDespesa = idDespesa;
        this.usuarioByIdUsuario = usuarioByIdUsuario;
        this.descricao = descricao;
        this.preco = preco;
    }

    public Integer getIdDespesa() {
        return this.idDespesa;
    }

    public void setIdDespesa(Integer idDespesa) {
        this.idDespesa = idDespesa;
    }

    public Usuario getUsuarioByIdUsuario() {
        return this.usuarioByIdUsuario;
    }

    public void setUsuarioByIdUsuario(Usuario usuarioByIdUsuario) {
        this.usuarioByIdUsuario = usuarioByIdUsuario;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Double getPreco() {
        return this.preco;
    }

    public void setPreco(Double preco) {
        this.preco = preco;
    }

}
