package rc.unesp.br.lcp.beans;
// Generated 27/07/2015 23:54:14 by Hibernate Tools 4.3.1

/**
 * Despesa generated by hbm2java
 */
public class Despesa implements java.io.Serializable {

    public static final String ID_DESPESA = "idDespesa";
    public static final String DESCRICAO = "descricao";
    public static final String PRECO = "preco";
    public static final String ID_USUARIO = "usuarioPagador";
    public static final String PAGO = "pago";

    private Integer idDespesa;
    private Usuario usuarioPagador;
    private String descricao;
    private Double preco;
    private boolean pago;

    public Despesa() {
    }

    public Despesa(Integer idDespesa, Usuario usuarioPagador, String descricao, Double preco, boolean pago) {
        this.idDespesa = idDespesa;
        this.usuarioPagador = usuarioPagador;
        this.descricao = descricao;
        this.preco = preco;
        this.pago = pago;
    }

    public Integer getIdDespesa() {
        return this.idDespesa;
    }

    public void setIdDespesa(Integer idDespesa) {
        this.idDespesa = idDespesa;
    }

    public Usuario getUsuarioPagador() {
        return this.usuarioPagador;
    }

    public void setUsuarioPagador(Usuario usuarioPagador) {
        this.usuarioPagador = usuarioPagador;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Double getPreco() {
        return this.preco;
    }

    public void setPreco(Double preco) {
        this.preco = preco;
    }

    public boolean isPago() {
        return pago;
    }

    public void setPago(boolean pago) {
        this.pago = pago;
    }

}
