package rc.unesp.br.lcp.beans;
// Generated 27/07/2015 23:54:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {

     public static final String ID_USUARIO = "idUsuario";
     public static final String NOME = "nome";
     public static final String APELIDO = "apelido";
     public static final String CPF = "cpf";
    
     private Integer idUsuario;
     private Contabancaria contabancaria;
     private String nome;
     private String apelido;
     private String cpf;
     private Date dataInicio;
     private Date dataTermino;
     private Integer situacaoUsuario;
     private String telefoneResidencial;
     private String telefoneCelular;
     private String email;
     private Set dividasForIdUsuarioDevedor = new HashSet(0);
     private Set dividasForIdUsuarioRecebedor = new HashSet(0);

    public Usuario() {
    }

    public Usuario(Contabancaria contabancaria, String nome, String apelido, String cpf, Date dataInicio, Date dataTermino, Integer situacaoUsuario, String telefoneResidencial, String telefoneCelular, String email, Set dividasForIdUsuarioDevedor, Set dividasForIdUsuarioRecebedor) {
       this.contabancaria = contabancaria;
       this.nome = nome;
       this.apelido = apelido;
       this.cpf = cpf;
       this.dataInicio = dataInicio;
       this.dataTermino = dataTermino;
       this.situacaoUsuario = situacaoUsuario;
       this.telefoneResidencial = telefoneResidencial;
       this.telefoneCelular = telefoneCelular;
       this.email = email;
       this.dividasForIdUsuarioDevedor = dividasForIdUsuarioDevedor;
       this.dividasForIdUsuarioRecebedor = dividasForIdUsuarioRecebedor;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Contabancaria getContabancaria() {
        return this.contabancaria;
    }
    
    public void setContabancaria(Contabancaria contabancaria) {
        this.contabancaria = contabancaria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getDataTermino() {
        return this.dataTermino;
    }
    
    public void setDataTermino(Date dataTermino) {
        this.dataTermino = dataTermino;
    }
    public Integer getSituacaoUsuario() {
        return this.situacaoUsuario;
    }
    
    public void setSituacaoUsuario(Integer situacaoUsuario) {
        this.situacaoUsuario = situacaoUsuario;
    }
    public String getTelefoneResidencial() {
        return this.telefoneResidencial;
    }
    
    public void setTelefoneResidencial(String telefoneResidencial) {
        this.telefoneResidencial = telefoneResidencial;
    }
    public String getTelefoneCelular() {
        return this.telefoneCelular;
    }
    
    public void setTelefoneCelular(String telefoneCelular) {
        this.telefoneCelular = telefoneCelular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getDividasForIdUsuarioDevedor() {
        return this.dividasForIdUsuarioDevedor;
    }
    
    public void setDividasForIdUsuarioDevedor(Set dividasForIdUsuarioDevedor) {
        this.dividasForIdUsuarioDevedor = dividasForIdUsuarioDevedor;
    }
    public Set getDividasForIdUsuarioRecebedor() {
        return this.dividasForIdUsuarioRecebedor;
    }
    
    public void setDividasForIdUsuarioRecebedor(Set dividasForIdUsuarioRecebedor) {
        this.dividasForIdUsuarioRecebedor = dividasForIdUsuarioRecebedor;
    }




}


