/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rc.unesp.br.lcp.view;

/**
 *
 * @author webster
 */
public class Lancamentos extends javax.swing.JFrame {

    /**
     * Creates new form Lancamentos
     */
    public Lancamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroupTipo = new javax.swing.ButtonGroup();
    tabbedPaneTipos = new javax.swing.JTabbedPane();
    panelContaColetiva = new javax.swing.JPanel();
    labelComprador = new javax.swing.JLabel();
    labelValor = new javax.swing.JLabel();
    labelDescricaoConta = new javax.swing.JLabel();
    scrollPaneDescricaoConta = new javax.swing.JScrollPane();
    textAreaDescricaoConta = new javax.swing.JTextArea();
    comboBoxComprador = new javax.swing.JComboBox();
    textValorConta = new javax.swing.JTextField();
    panelDivida = new javax.swing.JPanel();
    labelDevedor = new javax.swing.JLabel();
    labelRecebedor = new javax.swing.JLabel();
    labelValorDivida = new javax.swing.JLabel();
    labelDescricaoDivida = new javax.swing.JLabel();
    scrollPaneDescricaoDivida = new javax.swing.JScrollPane();
    textAreaDescricaoDivida = new javax.swing.JTextArea();
    comboBoxDevedor = new javax.swing.JComboBox();
    comboBoxRecebedor = new javax.swing.JComboBox();
    textValorDivida = new javax.swing.JTextField();
    panelTipoLancamento = new javax.swing.JPanel();
    radioButtonConta = new javax.swing.JRadioButton();
    radioButtonDivida = new javax.swing.JRadioButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Lançamentos");

    tabbedPaneTipos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    tabbedPaneTipos.setToolTipText("");

    panelContaColetiva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

    labelComprador.setText("Comprador:");

    labelValor.setText("Valor:");

    labelDescricaoConta.setText("Descrição:");

    textAreaDescricaoConta.setColumns(20);
    textAreaDescricaoConta.setRows(5);
    scrollPaneDescricaoConta.setViewportView(textAreaDescricaoConta);

    comboBoxComprador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout panelContaColetivaLayout = new javax.swing.GroupLayout(panelContaColetiva);
    panelContaColetiva.setLayout(panelContaColetivaLayout);
    panelContaColetivaLayout.setHorizontalGroup(
      panelContaColetivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelContaColetivaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelContaColetivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelComprador)
          .addComponent(labelValor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelContaColetivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(comboBoxComprador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(textValorConta, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelContaColetivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(labelDescricaoConta)
          .addComponent(scrollPaneDescricaoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    panelContaColetivaLayout.setVerticalGroup(
      panelContaColetivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelContaColetivaLayout.createSequentialGroup()
        .addGroup(panelContaColetivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelContaColetivaLayout.createSequentialGroup()
            .addGap(54, 54, 54)
            .addGroup(panelContaColetivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(labelComprador)
              .addComponent(comboBoxComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelContaColetivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(labelValor)
              .addComponent(textValorConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(panelContaColetivaLayout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(labelDescricaoConta)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(scrollPaneDescricaoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(41, 41, 41))
    );

    tabbedPaneTipos.addTab("Conta Coletiva", panelContaColetiva);

    panelDivida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

    labelDevedor.setText("Devedor:");

    labelRecebedor.setText("Recebedor:");

    labelValorDivida.setText("Valor:");

    labelDescricaoDivida.setText("Descrição:");

    textAreaDescricaoDivida.setColumns(20);
    textAreaDescricaoDivida.setRows(5);
    scrollPaneDescricaoDivida.setViewportView(textAreaDescricaoDivida);

    comboBoxDevedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    comboBoxRecebedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout panelDividaLayout = new javax.swing.GroupLayout(panelDivida);
    panelDivida.setLayout(panelDividaLayout);
    panelDividaLayout.setHorizontalGroup(
      panelDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDividaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelRecebedor)
          .addComponent(labelValorDivida)
          .addComponent(labelDevedor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(comboBoxDevedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(comboBoxRecebedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(textValorDivida, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDividaLayout.createSequentialGroup()
            .addComponent(labelDescricaoDivida)
            .addGap(116, 116, 116))
          .addComponent(scrollPaneDescricaoDivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    panelDividaLayout.setVerticalGroup(
      panelDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDividaLayout.createSequentialGroup()
        .addGroup(panelDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDividaLayout.createSequentialGroup()
            .addGap(45, 45, 45)
            .addGroup(panelDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(labelDevedor)
              .addComponent(comboBoxDevedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(labelRecebedor)
              .addComponent(comboBoxRecebedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(labelValorDivida)
              .addComponent(textValorDivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(panelDividaLayout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(labelDescricaoDivida)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(scrollPaneDescricaoDivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(41, 41, 41))
    );

    tabbedPaneTipos.addTab("Dívida", panelDivida);

    panelTipoLancamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Lançamento"));

    buttonGroupTipo.add(radioButtonConta);
    radioButtonConta.setText("Conta coletiva");
    radioButtonConta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        radioButtonContaActionPerformed(evt);
      }
    });

    buttonGroupTipo.add(radioButtonDivida);
    radioButtonDivida.setText("Dívida");

    javax.swing.GroupLayout panelTipoLancamentoLayout = new javax.swing.GroupLayout(panelTipoLancamento);
    panelTipoLancamento.setLayout(panelTipoLancamentoLayout);
    panelTipoLancamentoLayout.setHorizontalGroup(
      panelTipoLancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTipoLancamentoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelTipoLancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(radioButtonDivida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(radioButtonConta, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
        .addContainerGap())
    );
    panelTipoLancamentoLayout.setVerticalGroup(
      panelTipoLancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelTipoLancamentoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(radioButtonConta)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(radioButtonDivida)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(panelTipoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(tabbedPaneTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 372, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelTipoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tabbedPaneTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    tabbedPaneTipos.getAccessibleContext().setAccessibleName("Conta Coletiva");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void radioButtonContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonContaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_radioButtonContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lancamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lancamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lancamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lancamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lancamentos().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroupTipo;
  private javax.swing.JComboBox comboBoxComprador;
  private javax.swing.JComboBox comboBoxDevedor;
  private javax.swing.JComboBox comboBoxRecebedor;
  private javax.swing.JLabel labelComprador;
  private javax.swing.JLabel labelDescricaoConta;
  private javax.swing.JLabel labelDescricaoDivida;
  private javax.swing.JLabel labelDevedor;
  private javax.swing.JLabel labelRecebedor;
  private javax.swing.JLabel labelValor;
  private javax.swing.JLabel labelValorDivida;
  private javax.swing.JPanel panelContaColetiva;
  private javax.swing.JPanel panelDivida;
  private javax.swing.JPanel panelTipoLancamento;
  private javax.swing.JRadioButton radioButtonConta;
  private javax.swing.JRadioButton radioButtonDivida;
  private javax.swing.JScrollPane scrollPaneDescricaoConta;
  private javax.swing.JScrollPane scrollPaneDescricaoDivida;
  private javax.swing.JTabbedPane tabbedPaneTipos;
  private javax.swing.JTextArea textAreaDescricaoConta;
  private javax.swing.JTextArea textAreaDescricaoDivida;
  private javax.swing.JTextField textValorConta;
  private javax.swing.JTextField textValorDivida;
  // End of variables declaration//GEN-END:variables
}
